### ISSUE TITLE
Gitdir not defined

### ISSUE THREAD

**Issue by nalaso** [s3dman/dotfiles#1]
Gitdir not defined in dotfiles/autoload/plug.vim

/|\

**Comment by neb0lle** [comment]
I'm pretty sure that plug.vim is a self generated file by vim-plug. On my end everything works completely fine. Please elaborate the issue.

**Comment by alanalajs** [comment]
lo stdis cordac countsen duse rname

**Comment by NevilleJS** [comment]
CASANOVO#7247
